In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data/multipleChoiceResponses.csv', dtype='object')

In [9]:
df = df[[col_name for col_name in df.columns if not col_name.endswith('OTHER_TEXT') ]]

In [13]:
df.head().T.head(10)

,0,1,2,3,4
Time from Start to Finish (seconds),Duration (in seconds),710,434,718,621
Q1,What is your gender? - Selected Choice,Female,Male,Female,Male
Q2,What is your age (# years)?,45-49,30-34,30-34,35-39
Q3,In which country do you currently reside?,United States of America,Indonesia,United States of America,United States of America
Q4,What is the highest level of formal education ...,Doctoral degree,Bachelor’s degree,Master’s degree,Master’s degree
Q5,Which best describes your undergraduate major?...,Other,Engineering (non-computer focused),"Computer science (software engineering, etc.)","Social sciences (anthropology, psychology, soc..."
Q6,Select the title most similar to your current ...,Consultant,Other,Data Scientist,Not employed
Q7,In what industry is your current employer/cont...,Other,Manufacturing/Fabrication,I am a student,NaN
Q8,How many years of experience do you have in yo...,NaN,5-10,0-1,NaN
Q9,What is your current yearly compensation (appr...,NaN,"10-20,000","0-10,000",NaN

In [14]:
col_map = {'Time from Start to Finish (seconds)': 'duration',
           'Q1': 'gender',
           'Q2': 'age',
           'Q3': 'country',
           'Q4': 'education',
           'Q5': 'undergrad_major',
           'Q6': 'job_title',
           'Q7': 'industry',
           'Q8': 'experience_years',
           'Q9': 'salary',
           'Q10': 'use_ml',
           'Q11': }

In [ ]:
# Step 1. Rename columns into descriptive names and drop first row
df.columns = ['duration', 'gender', 'age', 'country', 'education', 'undergrad_major', 'job_title',
             ]

In [3]:
# Step 1. Remove rows without target variable
not_to_say = 'I do not wish to disclose my approximate yearly compensation'
outlier = 'What is your current yearly compensation (approximate $USD)?'
clean_df = df[~((pd.isnull(df['Q9'])) | (df['Q9'] == not_to_say) | (['Q9'] == outlier))]

In [4]:
clean_df.head(3).T

,0,2,3
Time from Start to Finish (seconds),Duration (in seconds),434,718
Q1,What is your gender? - Selected Choice,Male,Female
Q1_OTHER_TEXT,What is your gender? - Prefer to self-describe...,-1,-1
Q2,What is your age (# years)?,30-34,30-34
Q3,In which country do you currently reside?,Indonesia,United States of America
Q4,What is the highest level of formal education ...,Bachelor’s degree,Master’s degree
Q5,Which best describes your undergraduate major?...,Engineering (non-computer focused),"Computer science (software engineering, etc.)"
Q6,Select the title most similar to your current ...,Other,Data Scientist
Q6_OTHER_TEXT,Select the title most similar to your current ...,0,-1
Q7,In what industry is your current employer/cont...,Manufacturing/Fabrication,I am a student
Q7_OTHER_TEXT,In what industry is your current employer/cont...,-1,-1
Q8,How many years of experience do you have in yo...,5-10,0-1
Q9,What is your current yearly compensation (appr...,"10-20,000","0-10,000"
Q10,Does your current employer incorporate machine...,No (we do not use ML methods),I do not know
Q11_Part_1,Select any activities that make up an importan...,NaN,Analyze and understand data to influence produ...
Q11_Part_2,Select any activities that make up an importan...,NaN,NaN
Q11_Part_3,Select any activities that make up an importan...,NaN,NaN
Q11_Part_4,Select any activities that make up an importan...,NaN,NaN
Q11_Part_5,Select any activities that make up an importan...,NaN,NaN
Q11_Part_6,Select any activities that make up an importan...,None of these activities are an important part...,NaN
Q11_Part_7,Select any activities that make up an importan...,NaN,NaN
Q11_OTHER_TEXT,Select any activities that make up an importan...,-1,-1
Q12_MULTIPLE_CHOICE,What is the primary tool that you use at work ...,"Basic statistical software (Microsoft Excel, G...",Local or hosted development environments (RStu...
Q12_Part_1_TEXT,What is the primary tool that you use at work ...,1,-1
Q12_Part_2_TEXT,What is the primary tool that you use at work ...,-1,-1
Q12_Part_3_TEXT,What is the primary tool that you use at work ...,-1,-1
Q12_Part_4_TEXT,What is the primary tool that you use at work ...,-1,0
Q12_Part_5_TEXT,What is the primary tool that you use at work ...,-1,-1
Q12_OTHER_TEXT,What is the primary tool that you use at work ...,-1,-1
Q13_Part_1,Which of the following integrated development ...,NaN,NaN
...,...,...,...
Q47_Part_10,What methods do you prefer for explaining and/...,NaN,NaN
Q47_Part_11,What methods do you prefer for explaining and/...,NaN,NaN
Q47_Part_12,What methods do you prefer for explaining and/...,NaN,NaN
Q47_Part_13,What methods do you prefer for explaining and/...,NaN,NaN
Q47_Part_14,What methods do you prefer for explaining and/...,NaN,NaN
Q47_Part_15,What methods do you prefer for explaining and/...,NaN,NaN
Q47_Part_16,What methods do you prefer for explaining and/...,NaN,NaN
Q48,"Do you consider ML models to be ""black boxes"" ...",NaN,I am confident that I can explain the outputs ...
Q49_Part_1,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_2,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_3,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_4,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_5,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_6,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_7,What tools and methods do you use to make your...,NaN,Make sure the code is human-readable
Q49_Part_8,What tools and methods do you use to make your...,NaN,Define all random seeds
Q49_Part_9,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_10,What tools and methods do you use to make your...,NaN,Include a text file describing all dependencies
Q49_Part_11,What tools and methods do you use to make your...,NaN,NaN
Q49_Part_12,What tools and methods do you use to make your...,NaN,NaN
Q49_OTHER_TEXT,What tools and methods do you use to make your...,-1,-1
Q50_Part_1,What barriers prevent you from making your wor...,NaN,NaN
Q50_Part_2,What barriers prevent you from making your wor...,NaN,Too time-consuming
Q50_Part_3,What barriers prevent you from making your wor...,NaN,NaN
Q50_Part_4,What barriers prevent you from making your wor...,NaN,NaN
Q50_Part_5,What barriers prevent you from making your wor...,NaN,NaN
Q50_Part_6,What barriers prevent you from making your wor...,NaN,NaN
Q50_Part_7,What barriers prevent you from making your wor...,NaN,NaN
Q50_Part_8,What barriers prevent you from making your wor...,NaN,NaN
Q50_OTHER_TEXT,What barriers prevent you from making your wor...,-1,-1